[[Check]]
arch = "aarch64"
git-tree-sha1 = "5215a8edd918bb8c917db03b45198ceb11a3513c"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "bee225c74ccefef803e0bbbb02e8ebab3191dce1e121754221d00adad40f5bd6"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.aarch64-linux-gnu.tar.gz"
[[Check]]
arch = "aarch64"
git-tree-sha1 = "5a20141aead7137c9664c7ea8ce19324296c7def"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "e10fc52d33a303b02587b6bdaa6a40e8ecb935eff48eca3ed349afb2c86171dc"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.aarch64-linux-musl.tar.gz"
[[Check]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "689ae8dfecc3e6c943eea40d1f2a7694342f3418"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "f5b104a61a4b38b414da16ee647225da30f89cf622db1c9bde1176173f04a28c"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.armv7l-linux-gnueabihf.tar.gz"
[[Check]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11b3c781fbe76e637ca402afe9db67d21cb39046"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "6062fd69adfdfa797058b95c09b3ca78da5482b006f9757d1da7f7d3894fd725"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.armv7l-linux-musleabihf.tar.gz"
[[Check]]
arch = "i686"
git-tree-sha1 = "56f65a892159b7b3b1dae3596591d927279894e1"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "09dac3ec11e7957e7b03e5a3ab4d23a6a632c7a9c5dca13f1d3e00dcdb14b3b9"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.i686-linux-gnu.tar.gz"
[[Check]]
arch = "i686"
git-tree-sha1 = "3179bc3d0dd27c5a4a647cc5929df4836a28cf6b"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "1feed024c454894c4e429086e3200107cdb1c187ee0971f6b08fd9acdc7e9433"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.i686-linux-musl.tar.gz"
[[Check]]
arch = "i686"
git-tree-sha1 = "d1aaf37bcbe46ad4cc9f01e5a547b308c45f29a6"
os = "windows"

    [[Check.download]]
    sha256 = "b8d6edf04704518a16c6e85377abd382a70e4aaeb58a1250b6a2ba587b088b51"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.i686-w64-mingw32.tar.gz"
[[Check]]
arch = "powerpc64le"
git-tree-sha1 = "4d21d262265fe96d416d68d9bd59fbb74be6578a"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "1672c452c8742a9f70980e778623a2aa9d9f4ecd51304faa55e01d09457dca17"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.powerpc64le-linux-gnu.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "e87667b021cdbe44458160aa4c478c0704f30566"
os = "macos"

    [[Check.download]]
    sha256 = "34e3d28e0155cd172499d50fb73d60f2ffbf6992c319f8c22b50b50c35acfb4f"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.x86_64-apple-darwin.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "1db1d02f721de1495215f9ca23bd9c53a3d60539"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "8d674eb7649c23183ae4f9f895f762fc11f3123a8bb5f019f963016da6b04597"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.x86_64-linux-gnu.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "3984663d8f2016b85189d7b9cb5d68388a5a0e45"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "d0d4c0c1f936c503c9f8ad9e1f10f513c6ea2035a40f824d9674e322ceda1dac"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.x86_64-linux-musl.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "3828f82fd3f17109683566f302b8059994cd0617"
os = "freebsd"

    [[Check.download]]
    sha256 = "6b1c9ad8f9316ac50306f6b113c7f9598e16c7219e41e16fe78a97a8f8af98a3"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.x86_64-unknown-freebsd.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "2c856d954dd0d18d337b274bc7e238be3ef3748e"
os = "windows"

    [[Check.download]]
    sha256 = "affde374609e7205384c37c51d62ea17393fd2cbd2ab7e78d9709e60dc319ce9"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.2+0/Check.v0.15.2.x86_64-w64-mingw32.tar.gz"
