[[Check]]
arch = "aarch64"
git-tree-sha1 = "412c4b8ce3ac9b1806dfcf40d0ff9a183f0cf351"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "b5d538e2cc9aae95d91af700565b4046c2fab427eae025f057508af4059d764f"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.aarch64-linux-gnu.tar.gz"
[[Check]]
arch = "aarch64"
git-tree-sha1 = "891d7d4b2156fa20524f6ae32103755a88a78ebf"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "763b7e8fb63a9f4022d8eddb2ac4d3a8a9c3f39287b63f38749405bc47556642"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.aarch64-linux-musl.tar.gz"
[[Check]]
arch = "armv7l"
git-tree-sha1 = "7ccf2978eb3f6e0caaf39da83ba2f6f88cc6af1e"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "5ad2d8f135c55ae0c01ccea12cc800e434b3945e2c0ed4922171b763c3b09af0"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.armv7l-linux-gnueabihf.tar.gz"
[[Check]]
arch = "armv7l"
git-tree-sha1 = "89596eb32266456cfb1ab2f1e245baf7fc7211d6"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "f5cddbdec088c2e2cf07735ed909fbec0e5f19f4a047287e62879cff141f0c4c"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.armv7l-linux-musleabihf.tar.gz"
[[Check]]
arch = "i686"
git-tree-sha1 = "7148b9c77c48199dd25de4ba66c6244c3bb63df3"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "3b4f6e66d78e18281f319c0fc9cc3d054eea65bf5781e2f2ab5482cd48a0254b"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.i686-linux-gnu.tar.gz"
[[Check]]
arch = "i686"
git-tree-sha1 = "3e722da568015b3d5a5277fc9bf9237580de16a8"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "e328fa38f9ccd8d106c67a6c3e784ec3a37c98e98be52c6be95ede08ff2169d9"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.i686-linux-musl.tar.gz"
[[Check]]
arch = "i686"
git-tree-sha1 = "3da51407f5deae5cd9222e308023979ef528695f"
os = "windows"

    [[Check.download]]
    sha256 = "5a9e7afcda66a93a54dc05e3257c064ef8d2114ec2a09fdc9d3d834ddf9365f9"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.i686-w64-mingw32.tar.gz"
[[Check]]
arch = "powerpc64le"
git-tree-sha1 = "f360d941e83bfa2127851c328e6b5ac2c837bcaf"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "15196280784412f71360d6ac0727d296757a23c10416895a5a042c6a08c5c5b2"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.powerpc64le-linux-gnu.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "0bbe9a2d819099d48630e75fd38657dbf2892d0b"
os = "macos"

    [[Check.download]]
    sha256 = "1c0e3fec1cdd6c2d99bf30dbabd9d97d6abd719587fd0ac3daf4129db8335d6e"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.x86_64-apple-darwin14.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "44ef113c84b0f6f764c76820a15fa0a4e1f69e65"
libc = "glibc"
os = "linux"

    [[Check.download]]
    sha256 = "29b9d9b68f8bef21ded165e7564b4a6a8d220f7c7c25c8439451aa1a99aef16d"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.x86_64-linux-gnu.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "a7a18bec32a3b54d57a61700ec637ddd710df30f"
libc = "musl"
os = "linux"

    [[Check.download]]
    sha256 = "dc087c215f9422cd35333d55ac07969cbffd862d162b85a47bbaea6c03521567"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.x86_64-linux-musl.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "2edda357ce2fa571ba693f803012737988106ad3"
os = "freebsd"

    [[Check.download]]
    sha256 = "b89273d36a222bcbc7617e3e6440acaa19ce57d782b5ab97c46f8f85ced73af6"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Check]]
arch = "x86_64"
git-tree-sha1 = "093a11f97a700feeefd1988ca756ae6856854574"
os = "windows"

    [[Check.download]]
    sha256 = "b9e8f2c54ef71fd32cccb9cf9ba8cd96c3ac44c3a9f103a10b7a2581b4a47709"
    url = "https://github.com/JuliaBinaryWrappers/Check_jll.jl/releases/download/Check-v0.15.1+0/Check.v0.15.1.x86_64-w64-mingw32.tar.gz"
