# Autogenerated wrapper script for Check_jll for x86_64-apple-darwin
export libcheck

JLLWrappers.@generate_wrapper_header("Check")
JLLWrappers.@declare_library_product(libcheck, "@rpath/libcheck.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcheck,
        "lib/libcheck.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
